project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include("todo.urls",namespace="todo")),
    path('users/', include("users.urls", namespace="users"))
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"

urlpatterns =[
    path("", views.index, name = "index"),
    path("delete/<int:task_id>", views.delete, name = "delete")
]

users/urls.py
from django.urls import path
from . import views
app_name = "users"
urlpatterns = [
    path("", views.index, name = "index"),
    path("login", views.login_view, name = "login"),
    path("logout", views.logout_view, name = "logout"),
    path("register", views.register, name = "register")
]

todo/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.task}'

users/models.py
from django.db import models

# Create your models here.

todo/views.py
from django.shortcuts import render
from .models import Task
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task']
        labels = {'text': " add "}
        

def index(request):
    tasks = Task.objects.all()
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            HttpResponseRedirect("/")
            
    else:
        form = TaskForm()
    
    
    
    context = {
        "tasks": tasks,
        "form": form
    }
    return render(request, r"todo\index.html", context)
        
        
    
def delete(request, task_id):
    task = Task.objects.get(pk = task_id)
    task.delete()
    return HttpResponseRedirect(reverse("todo:index"))
    

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import send_mail
# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, r"users\user.html")
    
def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
    
        else:
            return render(request, "users\login.html", {"message":"invalid credentials"})
    return render(request, "users\login.html")


def logout_view(request):
    logout(request)
    return render(request, r"users\login.html", {
        "message":"logged out"
    })
    
    
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        email = request.POST["email"]
        confirm_password = request.POST["confirm password"]
        if password == confirm_password:
            user = User.objects.create_user(username, email, password)
            user.save()
            send_mail('account activation', 'your account has been sucessfully created','olabodeezekiel2018@yahoo.com', [ email ], fail_silently=False)
            return HttpResponseRedirect(reverse("users:login"))
            
    return render(request, r"users\register.html")

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'todo\styles.css' %}" rel="stylesheet" >
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<div class="addiv">
    <h1 class="word">todo list</h1><form action="{% url 'todo:index' %}" method="POST" id="addform">
   
    {% csrf_token %}
    {{ form }}
    <button class="addsub">Add Task</button></div>
</form>


    {% block body %}
{% endblock %}
</body>
</html>

todo/templates/todo/index.html
{% extends 'todo\base.html' %}

{% block body %}
{% for task in tasks %}
<div class="tasks">{{ task }}
    <a href="{% url 'todo:delete' task.id %}"><button class="del">delete</button></a>

{% empty %}
<h1>try adding task</h1>
{% endfor %}</div>


{% endblock %}

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head><link href="{% static 'users\general.css' %}"rel="stylesheet" >
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends "users\base.html" %}
{% block body %}
{% if message %}
<div>{{ message }}</div>
{% endif %}
<form action="{% url 'users:login' %}" method="POST" id="loginform">
{% csrf_token %}
<div class="logdiv">
    username: <input type="username" name="username"></br>
</div>
<div class="logdiv">
    password: <input type="password" name="password" >
</div>
<div class="logdiv">
    <input type="submit", value="login">
</div>
</form>


<p class="reglink"><a href="{% url 'users:register' %}">register here</a></p>
{% endblock %}

users/templates/users/register.html
{% extends "users\base.html" %}
{% block body %}


<form action="{% url 'users:register' %}" method="POST" id="registrationform">
{% csrf_token %}
<div class="regdiv"><h3>Register</h3></div>
<div class="regdiv"><label for="username" class="title">username:</label>
 <input type="username" name="username" /></div>
 <div class="regdiv"><label for="email" class="title">email:</label>
<input type="email" name="email" /></div>
<div class="regdiv"><label for="password" class="title">password:</label>
<input type="password" name="password" /></p></div>
<div class="regdiv"><label for="confirm password" class="title">confirm password:</label>
<input type="password" name="confirm password"></p></div>
<div class="regdiv"><input type="submit" value="register" id="submit"></div>
</form>
{% endblock %}

users/templates/users/user.html
{% extends "users\base.html" %}
{% block body %}

<h1>Welcome, {{ request.user.first_name }}</h1>

<ul>
    <li>username: {{ request.user.username }}</li>
    <li>Email: {{ request.user.email }}</li>
</ul>
<a href="{% url 'users:logout' %}">log out</a>
 
{% endblock %}